List<String> districts = <String>[
  "Colombo",
  "Gampaha",
  "Kalutara",
  "Kandy",
  "Matale",
  "Nuwara Eliya",
  "Galle",
  "Matara",
  "Hambantota",
  "Jaffna",
  "Kilinochchi",
  "Mannar",
  "Vavuniya",
  "Mullaitivu",
  "Batticaloa",
  "Ampara",
  "Trincomalee",
  "Kurunegala",
  "Puttalam",
  "Anuradhapura",
  "Polonnaruwa",
  "Badulla",
  "Moneragala",
  "Ratnapura",
  "Kegalle",
];

List<String> provinces = <String>[
  "Central Province",
  "Eastern Province",
  "Southern Province",
  "Uva Province",
  "Sabaragamuwa Province",
  "North Western Province",
  "North Central Province",
  "Nothern Province",
  "Western Province",
];
